export {default as Home } from './Home'
export {default as Games} from './Games'
export {default as SpinTheWheel} from './SpinTheWheel'
export {default as ScratchNWin} from './ScratchNWin'
export {default as ShakeNWin} from './ShakeNWin'
export {default as LuckyBox} from './LuckyBox'
export {default as LuckyCard} from './LuckyCard'