export {default as Card} from './card'
export {default as Header} from './header'
export {default as WheelofSpin} from './spinWeel'
export {default as Modal} from './modals'
export {default as BoxCard} from './box'